
 % - - - - define predictors
model1.predictors = {'mEsentOns'}; % intercept1 model, sentence onset only
model1.permuted = {'mEsentOns'};
model1.name = 'model1';

model2.predictors = {'mEsentOns',... % intercep2 model, sentence onset + peakRates 
    'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB'}; 
model2.permuted = {'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB'}; 
model2.name = 'model2';

model3.predictors = {'mEsentOns',... % sentence onset + stress
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateUnsB', 'mEpRateStrB'};
model3.permuted = {'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateUnsB', 'mEpRateStrB'};
model3.name = 'model3';

model4.predictors = {'mEsentOns',... % sentence onset + rhythm
    'mEpRateRegM', 'mEpRateIrrM',...
    'mEpRateRegB', 'mEpRateIrrB'};
model4.permuted = {'mEpRateRegM', 'mEpRateIrrM',...
    'mEpRateRegB', 'mEpRateIrrB'};
model4.name = 'model4';

model5.predictors = {'mEsentOns',... % sentence onset + rhythm + stress
    'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB'};
model5.permuted = { 'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB'};
model5.name = 'model5';

model6.predictors = {'mEsentOns',... % sentence onset + rhythm + stress + interaction
    'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB',...
    'pRateUnsIrrM', 'pRateUnsRegM',...
     'pRateStrIrrM', 'pRateStrRegM',...
     'pRateUnsIrrB', 'pRateUnsRegB',...
     'pRateStrIrrB', 'pRateStrRegB'};
 model6.permuted = {'mEpRateIrrM', 'mEpRateRegM',...
    'mEpRateUnsM', 'mEpRateStrM',...
    'mEpRateIrrB', 'mEpRateRegB',...
    'mEpRateUnsB', 'mEpRateStrB',...
    'pRateUnsIrrM', 'pRateUnsRegM',...
     'pRateStrIrrM', 'pRateStrRegM',...
     'pRateUnsIrrB', 'pRateUnsRegB',...
     'pRateStrIrrB', 'pRateStrRegB'};
  model6.name = 'model6';
